[package]
name = "workout-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.41", features = ["derive"] }
hashbrown = "0.15.5"
itertools = "0.14.0"
petgraph = "0.8.2"
thiserror = "2.0.16"
